-- SQL для создания таблицы параметров товаров
-- Запустите в Supabase SQL Editor

-- Таблица параметров (справочник)
CREATE TABLE IF NOT EXISTS product_parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  unit TEXT DEFAULT '',
  description TEXT DEFAULT '',
  category_hint TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Уникальный индекс на название
CREATE UNIQUE INDEX IF NOT EXISTS product_parameters_name_unique ON product_parameters (name);

-- RLS
ALTER TABLE product_parameters ENABLE ROW LEVEL SECURITY;

-- Политики: параметры читает кто угодно, изменяет только сервис-ключ
CREATE POLICY "Public Read Parameters" ON product_parameters FOR SELECT USING (true);

-- Заполнение базовыми параметрами из описаний товаров
INSERT INTO product_parameters (name, unit, category_hint, sort_order) VALUES
  ('Диаметр', 'мм', 'Арматура, Труба', 1),
  ('Класс / Стандарт', '', 'Арматура', 2),
  ('Длина хлыста', 'мм', 'Арматура', 3),
  ('Марка стали', '', 'Общее', 4),
  ('Вес п/м', 'кг', 'Общее', 5),
  ('Хлыстов в тонне', 'шт', 'Арматура', 6),
  ('Метров в тонне', 'м', 'Общее', 7),
  ('Сечение', 'мм', 'Труба профильная', 8),
  ('Толщина стенки', 'мм', 'Труба', 9),
  ('Длина трубы', 'мм', 'Труба', 10),
  ('ГОСТ / Стандарт', '', 'Общее', 11),
  ('Тип / Профиль', '', 'Балка, Швеллер', 12),
  ('Высота', 'мм', 'Балка', 13),
  ('Длина', 'мм', 'Общее', 14),
  ('Толщина листа', 'мм', 'Лист', 15),
  ('Раскрой (Ширина × Длина)', 'мм', 'Лист', 16),
  ('Номер швеллера', '', 'Швеллер', 17),
  ('Тип граней полок', '', 'Швеллер', 18),
  ('Размер полок', 'мм', 'Уголок', 19),
  ('Тип уголка', '', 'Уголок', 20),
  ('Марка / Профиль', '', 'Кровля', 21),
  ('Покрытие / Цвет', '', 'Кровля', 22),
  ('Внешний диаметр', 'мм', 'Труба', 23),
  ('Поверхность / Профиль', '', 'Арматура', 24),
  ('Тип полок', '', 'Балка', 25)
ON CONFLICT (name) DO NOTHING;
